version: '3'

services:
  ctr-db:
    image: mysql:5.7
    volumes:
      - db-vol:/var/lib/mysql
    env_file:
      .ctr-bd-var-env.yaml
    networks:
      - wp-networks
    restart: always

  ctr-wp:
    image: wordpress:latest
    ports:
      - "3000:80"
    env_file:
      - .ctr-wp-var-env.yaml
    networks:
      - wp-net
    restart: always
    depends_on:
      - ctr-db

  py-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:7000"
    restart: always

volumes:
  db-vol: {}
networks:
  wp-net: {}



